name: Auto Update 

on:    
  workflow_dispatch:
  schedule:
      - cron: "30 6 * * *"
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clone the Python script.
        run: curl ${{ secrets.SCRIPT }} >> main.py

      - name: Run python script.
        run: |
          pip install jinja2 pathlib pytz datetime pip 
          python main.py
          rm main.py
        id: update-time

      - name: Update the README file.
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.update-time.outputs.UPDATED_TIME }}
          commit_options: '--amend'
          push_options: '--force'
          skip_fetch: true
